/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type CollectionServerEventSettingsTransformer from '#app/collection/transformers/server_event_settings_transformer'
import type IdentityAccountDetailsTransformer from '#app/identity/transformers/account_details_transformer'
import type UserTransformer from '#app/transformers/user_transformer'
import type WebsitesWebsiteEventsTransformer from '#app/websites/transformers/website_events_transformer'
import type WebsitesWebsiteOverviewTransformer from '#app/websites/transformers/website_overview_transformer'
import type InertiaMiddleware from '#app/middleware/inertia_middleware'

export namespace Data {
  export namespace Collection {
    export type ServerEventSettings = InferData<CollectionServerEventSettingsTransformer>
    export namespace ServerEventSettings {
      export type Variants = InferVariants<CollectionServerEventSettingsTransformer>
    }
  }
  export namespace Identity {
    export type AccountDetails = InferData<IdentityAccountDetailsTransformer>
    export namespace AccountDetails {
      export type Variants = InferVariants<IdentityAccountDetailsTransformer>
    }
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export namespace Websites {
    export type WebsiteEvents = InferData<WebsitesWebsiteEventsTransformer>
    export namespace WebsiteEvents {
      export type Variants = InferVariants<WebsitesWebsiteEventsTransformer>
    }
    export type WebsiteOverview = InferData<WebsitesWebsiteOverviewTransformer>
    export namespace WebsiteOverview {
      export type Variants = InferVariants<WebsitesWebsiteOverviewTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
