/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  collection: {
    RecordBrowserEvent: () => import('#app/collection/controllers/record_browser_event_controller'),
  },
  identity: {
    Account: () => import('#app/identity/controllers/account_controller'),
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
    RegisterUser: () => import('#app/identity/controllers/register_user_controller'),
  },
  websites: {
    CreateWebsite: () => import('#app/websites/controllers/create_website_controller'),
    Website: () => import('#app/websites/controllers/website_controller'),
    WebsiteEvents: () => import('#app/websites/controllers/website_events_controller'),
  },
}
