/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  collection: {
    CreateServerKey: () => import('#app/collection/controllers/create_server_key_controller'),
    RecordBrowserEvent: () => import('#app/collection/controllers/record_browser_event_controller'),
    RecordServerEvent: () => import('#app/collection/controllers/record_server_event_controller'),
    RevokeServerKey: () => import('#app/collection/controllers/revoke_server_key_controller'),
    ServerEventSettings: () => import('#app/collection/controllers/server_event_settings_controller'),
  },
  funnels: {
    CreateFunnel: () => import('#app/funnels/controllers/create_funnel_controller'),
    EditFunnel: () => import('#app/funnels/controllers/edit_funnel_controller'),
    FunnelReport: () => import('#app/funnels/controllers/funnel_report_controller'),
    WebsiteFunnels: () => import('#app/funnels/controllers/website_funnels_controller'),
  },
  identity: {
    Account: () => import('#app/identity/controllers/account_controller'),
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
    RegisterUser: () => import('#app/identity/controllers/register_user_controller'),
  },
  websites: {
    CreateWebsite: () => import('#app/websites/controllers/create_website_controller'),
    UpdateWebsiteIdentityMode: () => import('#app/websites/controllers/update_website_identity_mode_controller'),
    Website: () => import('#app/websites/controllers/website_controller'),
    WebsiteEvents: () => import('#app/websites/controllers/website_events_controller'),
  },
}
