/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  collection: {
    CreateServerKey: () => import('#app/collection/controllers/create_server_key_controller'),
    RecordBrowserEvent: () => import('#app/collection/controllers/record_browser_event_controller'),
    RecordServerEvent: () => import('#app/collection/controllers/record_server_event_controller'),
    RevokeServerKey: () => import('#app/collection/controllers/revoke_server_key_controller'),
  },
  funnels: {
    CreateFunnel: () => import('#app/funnels/controllers/create_funnel_controller'),
    EditFunnel: () => import('#app/funnels/controllers/edit_funnel_controller'),
    FunnelReport: () => import('#app/funnels/controllers/funnel_report_controller'),
    WebsiteFunnels: () => import('#app/funnels/controllers/website_funnels_controller'),
  },
  identity: {
    Account: () => import('#app/identity/controllers/account_controller'),
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
    OwnerDataExport: () => import('#app/identity/controllers/owner_data_export_controller'),
    RegisterUser: () => import('#app/identity/controllers/register_user_controller'),
  },
  shared: {
    Liveness: () => import('#app/shared/controllers/liveness_controller'),
    Readiness: () => import('#app/shared/controllers/readiness_controller'),
  },
  websites: {
    AddAllowedDomain: () => import('#app/websites/controllers/add_allowed_domain_controller'),
    CreateCollectionKey: () => import('#app/websites/controllers/create_collection_key_controller'),
    CreateWebsite: () => import('#app/websites/controllers/create_website_controller'),
    RemoveAllowedDomain: () => import('#app/websites/controllers/remove_allowed_domain_controller'),
    RevokeCollectionKey: () => import('#app/websites/controllers/revoke_collection_key_controller'),
    UpdateWebsiteIdentityMode: () => import('#app/websites/controllers/update_website_identity_mode_controller'),
    UpdateWebsiteRetention: () => import('#app/websites/controllers/update_website_retention_controller'),
    Website: () => import('#app/websites/controllers/website_controller'),
    WebsiteEvents: () => import('#app/websites/controllers/website_events_controller'),
    WebsiteSettings: () => import('#app/websites/controllers/website_settings_controller'),
  },
}
