/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Events {
  anonymous_id: string | null;
  distinct_id: string | null;
  id: string;
  name: string;
  occurred_at: Timestamp;
  path: string;
  properties: Json | null;
  received_at: Generated<Timestamp>;
  referrer: string | null;
  session_id: string | null;
  source: number;
  utm_campaign: string | null;
  utm_medium: string | null;
  utm_source: string | null;
  website_id: string;
}

export interface Funnels {
  conversion_window_seconds: number;
  created_at: Generated<Timestamp>;
  id: string;
  identity_kind: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  website_id: string;
}

export interface FunnelSteps {
  event_name: string;
  filter: Json | null;
  funnel_id: string;
  position: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string | null;
  password: string;
  updated_at: Timestamp | null;
}

export interface Websites {
  allowed_domain: string;
  created_at: Generated<Timestamp>;
  id: string;
  identity_mode: Generated<string>;
  name: string;
  timezone: Generated<string>;
  tracking_id: string;
  workspace_id: string;
}

export interface WebsiteServerKeys {
  created_at: Generated<Timestamp>;
  id: string;
  prefix: string;
  revoked_at: Timestamp | null;
  secret_hash: string;
  website_id: string;
}

export interface Workspaces {
  created_at: Generated<Timestamp>;
  id: string;
  owner_user_id: string;
}

export interface DB {
  events: Events;
  funnel_steps: FunnelSteps;
  funnels: Funnels;
  users: Users;
  website_server_keys: WebsiteServerKeys;
  websites: Websites;
  workspaces: Workspaces;
}
