name: boring-analytics-dev

services:
  database:
    image: postgres:18.0-alpine3.22
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -h 127.0.0.1 -U app -d app']
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  postgres-data:
